In [4]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
#a partir de uuna lista,tupla y dict

In [6]:
#Crear en base a un diccionario

data ={

   'Nombre':['Juan','Maria','Pedro'],
    'Edad':[25,30,35]
   }

df = pd.DataFrame(data)

In [7]:
df

  Nombre  Edad
0   Juan    25
1  Maria    30
2  Pedro    35

In [9]:

df = pd.read_csv('../utils/data/data.csv')

In [10]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [11]:
#Lectura de archivo semiestructurado
df = pd.read_json('../utils/data/data.json')

In [12]:
df

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona
2  Pedro    35    Sevilla

# Metodos con Dataframe

In [14]:
df.describe()

       edad
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [ ]:
df.head(2)# Primeros Valores

  nombre  edad     ciudad
0   Juan    25     Madrid
1  María    30  Barcelona

In [18]:
df.tail(2)

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

In [19]:
df.columns

Index(['nombre', 'edad', 'ciudad'], dtype='str')

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
# Contabilizar
df.count()

nombre    3
edad      3
ciudad    3
dtype: int64

# Acceder con valores DF

In [25]:
df['ciudad']


df[['ciudad','edad']]

      ciudad  edad
0     Madrid    25
1  Barcelona    30
2    Sevilla    35

In [28]:
#Por un indice
print(df.loc[0])

nombre      Juan
edad          25
ciudad    Madrid
Name: 0, dtype: object

In [29]:
print(df.loc[[0,2]])

  nombre  edad   ciudad
0   Juan    25   Madrid
2  Pedro    35  Sevilla

In [33]:
print(df[df['edad']>25])

  nombre  edad     ciudad
1  María    30  Barcelona
2  Pedro    35    Sevilla

# Agregaciones

In [35]:
# Agrpar datos por columnas y usar funciones

data ={
'Grupo':['A','A','B','B'],
'Valor':[10,20,30,40]
}

df =pd.DataFrame(data)

#Calcular el promedio por grupo
promedio_por_grupo = df.groupby('Grupo').mean()

print(promedio_por_grupo)

#Calcular la suma por grupo
suma_por_grupo = df.groupby('Grupo').sum()
print(suma_por_grupo)

       Valor
Grupo
A       15.0
B       35.0
       Valor
Grupo
A         30
B         70

In [41]:
df = pd.read_csv('../utils/data/data')

df

   nombre|edad|ciudad
0        Juan||Madrid
1  María|30|Barcelona
2    Pedro|35|Sevilla

In [ ]:
#Elimnar las filas
df_sin_na = df.dropna()
print(df_sin_na)


print('\n')

#reemplazar los valores
df_completo = df.fillna(value=0)
print(df_completo)

print('\n')

   nombre|edad|ciudad
0        Juan||Madrid
1  María|30|Barcelona
2    Pedro|35|Sevilla


   nombre|edad|ciudad
0        Juan||Madrid
1  María|30|Barcelona
2    Pedro|35|Sevilla

# Funciones en un Dataframe

In [47]:
data = {
    'A': [1, 2, 3, 4],
    'B': [6, 7, 8, 9]
}

df = pd.DataFrame(data)


df

   A  B
0  1  6
1  2  7
2  3  8
3  4  9

In [48]:
df['A_doble'] = df['A'].apply(lambda x: x * 2)
print(df)

   A  B  A_doble
0  1  6        2
1  2  7        4
2  3  8        6
3  4  9        8

In [49]:
# Definimos una función que multiplica por 2 un valor dado
def multiplo2(x):
    return x * 2

# Aplicamos la función 'multiplo2' a la columna 'A' usando .apply()
# El resultado se guarda en una nueva columna llamada 'A_doble2'
df['A_doble2'] = df['A'].apply(multiplo2)

# Mostramos el DataFrame resultante
df

   A  B  A_doble  A_doble2
0  1  6        2         2
1  2  7        4         4
2  3  8        6         6
3  4  9        8         8

In [51]:
df['suma'] = df.apply(lambda row: row['A'] + row['B'], axis=1)

df

   A  B  A_doble  A_doble2  suma
0  1  6        2         2     7
1  2  7        4         4     9
2  3  8        6         6    11
3  4  9        8         8    13

In [52]:
def suma(row):
    return  row['A'] + row['B']

# Aplicamos la función definida a cada fila usando axis=1
df['suma2'] = df.apply(suma, axis=1)


df

   A  B  A_doble  A_doble2  suma  suma2
0  1  6        2         2     7      7
1  2  7        4         4     9      9
2  3  8        6         6    11     11
3  4  9        8         8    13     13