In [1]:
# Se importa la biblioteca 'pandas' para manipulación y análisis de datos en tablas.
import pandas as pd
# Se importa la biblioteca 'sqlalchemy' para conectar y gestionar bases de datos.
import sqlalchemy as db
# Se importa la función 'text' de sqlalchemy para construir consultas SQL.
from sqlalchemy import text

In [2]:
# Crea un motor de base de datos para conectarse a MySQL.
# La cadena de conexión incluye el dialecto (mysql), usuario (root), contraseña (root),
# dirección del host (127.0.0.1), puerto (3310) y el nombre de la base de datos (db_movies_netflix_transact).
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/db_movies_netflix_transact")
# Establece una conexión con la base de datos utilizando el motor creado.
conn = engine.raw_connection()

# Cargamos datos a la dimension Movie

In [3]:
query = """
SELECT 
    movie.movieID as movieID, movie.movieTitle as title, movie.releaseDate as releaseDate, 
    gender.name as gender , person.name as participantName, participant.participantRole as roleparticipant 
FROM movie 
INNER JOIN participant 
ON movie.movieID=participant.movieID
INNER JOIN person
ON person.personID = participant.personID
INNER JOIN movie_gender 
ON movie.movieID = movie_gender.movieID
INNER JOIN gender 
ON movie_gender.genderID = gender.genderID
"""

In [4]:
# Carga los resultados de la consulta SQL en un DataFrame de pandas llamado 'movies_data'.
# La consulta 'query' se ejecuta en la conexión 'conn'.
movies_data=pd.read_sql(query, con=conn) 
# Convierte la columna 'movieID' a tipo de dato entero.
movies_data["movieID"]=movies_data["movieID"].astype('int')
# Muestra el DataFrame 'movies_data' con los cambios aplicados.
movies_data

/tmp/ipykernel_41901/479168223.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  movies_data=pd.read_sql(query, con=conn)

,movieID,title,releaseDate,gender,participantName,roleparticipant
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director

In [5]:
# Carga un archivo CSV llamado 'Awards_movie.csv' en un DataFrame de pandas.
movies_award=pd.read_csv("./data/Awards_movie.csv")
# Convierte la columna 'movieID' a tipo de dato entero.
movies_award["movieID"]=movies_award["movieID"].astype('int')
# Renombra la columna 'Aware' a 'Award' en el DataFrame.
movies_award.rename(columns={"Aware":"Award"}, inplace=True) 
# Muestra el DataFrame 'movies_award'.
movies_award

    movieID  IdAward   Award
0  80210920        0   Oscar
1  81157374        1  Grammy
2  80192187        2   Oscar

In [6]:
# Realiza una unión (merge) de los DataFrames 'movies_data' y 'movies_award'.
# La unión se realiza en la columna común 'movieID'.
movie_data=pd.merge(movies_data,movies_award,
                     left_on="movieID", 
                     right_on="movieID")
# Muestra el DataFrame resultante de la unión, llamado 'movie_data'.
movie_data

,movieID,title,releaseDate,gender,participantName,roleparticipant,IdAward,Award
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [7]:
# Crea un motor de base de datos para conectarse a una base de datos MySQL.
# La cadena de conexión especifica el dialecto, usuario, contraseña, dirección del host, puerto y el nombre de la base de datos 'dw_netflix'.
engine = db.create_engine("mysql://root:root@127.0.0.1:3310/dw_netflix")
# Establece una conexión con la base de datos utilizando el motor creado.
conn = engine.connect()

In [8]:
# Renombra las columnas del DataFrame 'movie_data'.
# 'releaseDate' se cambia a 'releaseMovie' y 'Award' se cambia a 'awardMovie'.
movie_data = movie_data.rename(columns={'releaseDate': 'releaseMovie', 'Award': 'awardMovie'})
movie_data

,movieID,title,releaseMovie,gender,participantName,roleparticipant,IdAward,awardMovie
0,80192187,Triple Frontier,2019-04-12,Action,Joseph Chavez Pineda,Actor,2,Oscar
1,80210920,The Mother,2023-01-05,Drama,Maria Alejandra Navarro,Actor,0,Oscar
2,81157374,Run,2021-05-21,Adventure,aria Lopez Gutierrez,Director,1,Grammy

In [9]:
# Elimina la columna 'IdAward' del DataFrame 'movie_data'.
movie_data = movie_data.drop(columns=['IdAward'])

In [10]:
# Carga los datos del DataFrame 'movie_data' en la tabla 'dimMovie' de la base de datos.
# La conexión a la base de datos se realiza a través de 'conn'.
# 'if_exists='append'' indica que si la tabla ya existe, se agregarán las nuevas filas al final.
# 'index=False' evita que el índice del DataFrame se escriba como una columna en la tabla.
movie_data.to_sql('dimMovie',conn,if_exists='append', index=False)
movie_data

IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry '80192187' for key 'dimMovie.PRIMARY'")
[SQL: INSERT INTO `dimMovie` (`movieID`, title, `releaseMovie`, gender, `participantName`, roleparticipant, `awardMovie`) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: [(80192187, 'Triple Frontier', datetime.date(2019, 4, 12), 'Action', 'Joseph Chavez Pineda', 'Actor', 'Oscar'), (80210920, 'The Mother', datetime.date(2023, 1, 5), 'Drama', 'Maria Alejandra Navarro', 'Actor', 'Oscar'), (81157374, 'Run', datetime.date(2021, 5, 21), 'Adventure', 'aria Lopez Gutierrez', 'Director', 'Grammy')]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

# Cargamos datos a la dimension USER

In [11]:
# Carga un archivo CSV llamado 'users.csv' en un DataFrame de pandas, utilizando '|' como separador.
users = pd.read_csv("./data/users.csv", sep='|')
# Muestra el DataFrame 'users' cargado.
users

      idUser     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [12]:
# Renombra la columna 'idUser' a 'userID' en el DataFrame 'users'.
users = users.rename(columns={'idUser': 'userID'})
# Muestra el DataFrame 'users' con la columna renombrada.
users

      userID     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [21]:
# Carga los datos del DataFrame 'users' en la tabla 'dimUser' de la base de datos.
# 'if_exists='append'' agrega los datos al final de la tabla si ya existe.
# 'index=False' evita que el índice del DataFrame se suba como una columna.
users.to_sql('dimUser', conn_dw, if_exists = 'append', index=False)

NameError: name 'conn_dw' is not defined

# Cargamos datos a la tabla de hechos

In [ ]:
users = pd.read_csv('./data/users.csv', sep='|')

users

      idUser     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [25]:
# Renombra la columna 'idUser' a 'userID' en el DataFrame 'users'.
users = users.rename(columns={'idUser': 'userID'})
# Muestra el DataFrame 'users' con la columna renombrada.
users

      userID     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

In [26]:
# Carga los datos del DataFrame 'users' en la tabla 'dimUser' de la base de datos.
# 'if_exists='append'' agrega los datos al final de la tabla si ya existe.
# 'index=False' evita que el índice del DataFrame se suba como una columna.
users.to_sql('dimUser',conn,if_exists='append', index=False)

IntegrityError: (MySQLdb.IntegrityError) (1062, "Duplicate entry '1002331' for key 'dimUser.PRIMARY'")
[SQL: INSERT INTO `dimUser` (`userID`, username, country, subscription) VALUES (%s, %s, %s, %s)]
[parameters: [(1002331, 'user123', 'USA', 'Premium'), (1002332, 'gamerGirl97', 'Canada', 'Basic'), (1002333, 'techMaster', 'UK', 'Premium'), (1002334, 'soccerFan', 'Brazil', 'Basic'), (1002335, 'travelBug', 'Australia', 'Premium'), (1002336, 'musicLover', 'France', 'Basic'), (1002337, 'foodie88', 'Italy', 'Premium'), (1002338, 'bookWorm23', 'Germany', 'Basic')  ... displaying 10 of 20 total bound parameter sets ...  (10023319, 'homeChef', 'NewZealand', 'Premium'), (10023320, 'yogiMaster', 'Thailand', 'Basic')]]
(Background on this error at: https://sqlalche.me/e/20/gkpj)

In [23]:
users = users.rename(columns = {'idUser':'userID'})
users

      userID     username      country subscription
0    1002331      user123          USA      Premium
1    1002332  gamerGirl97       Canada        Basic
2    1002333   techMaster           UK      Premium
3    1002334    soccerFan       Brazil        Basic
4    1002335    travelBug    Australia      Premium
5    1002336   musicLover       France        Basic
6    1002337     foodie88        Italy      Premium
7    1002338   bookWorm23      Germany        Basic
8    1002339  fitnessJunk       Mexico      Premium
9   10023310    movieBuff        Japan        Basic
10  10023311  artAficiona        Spain      Premium
11  10023312   petLover99  Netherlands        Basic
12  10023313  fashionista   SouthKorea      Premium
13  10023314  codingNinja        India        Basic
14  10023315  natureLover       Norway      Premium
15  10023316  coffeeAddct     Colombia        Basic
16  10023317     beachBum      Bahamas      Premium
17  10023318  skiEnthusst  Switzerland        Basic
18  10023319     homeChef   NewZealand      Premium
19  10023320   yogiMaster     Thailand        Basic

# Cargamos datos a la tabla de hechos

In [28]:
# Crea una Serie de pandas 'users_id' que contiene los valores de la columna 'idUser' del DataFrame 'users'.
users_id = users["userID"]

# Crea una Serie de pandas 'movies_id' que contiene los valores de la columna 'movieID' del DataFrame 'movies_data'.
movies_id = movies_data["movieID"]

In [31]:
# Realiza un producto cartesiano (cross merge) entre las Series 'users_id' y 'movies_id'.
# Esto crea un DataFrame donde cada 'userID' se empareja con cada 'movieID'.
watchs_data=pd.merge(users_id,movies_id, how="cross")
# Muestra el DataFrame resultante 'watchs_data'.
watchs_data

      userID   movieID
0    1002331  80192187
1    1002331  80210920
2    1002331  81157374
3    1002332  80192187
4    1002332  80210920
5    1002332  81157374
6    1002333  80192187
7    1002333  80210920
8    1002333  81157374
9    1002334  80192187
10   1002334  80210920
11   1002334  81157374
12   1002335  80192187
13   1002335  80210920
14   1002335  81157374
15   1002336  80192187
16   1002336  80210920
17   1002336  81157374
18   1002337  80192187
19   1002337  80210920
20   1002337  81157374
21   1002338  80192187
22   1002338  80210920
23   1002338  81157374
24   1002339  80192187
25   1002339  80210920
26   1002339  81157374
27  10023310  80192187
28  10023310  80210920
29  10023310  81157374
30  10023311  80192187
31  10023311  80210920
32  10023311  81157374
33  10023312  80192187
34  10023312  80210920
35  10023312  81157374
36  10023313  80192187
37  10023313  80210920
38  10023313  81157374
39  10023314  80192187
40  10023314  80210920
41  10023314  81157374
42  10023315  80192187
43  10023315  80210920
44  10023315  81157374
45  10023316  80192187
46  10023316  80210920
47  10023316  81157374
48  10023317  80192187
49  10023317  80210920
50  10023317  81157374
51  10023318  80192187
52  10023318  80210920
53  10023318  81157374
54  10023319  80192187
55  10023319  80210920
56  10023319  81157374
57  10023320  80192187
58  10023320  80210920
59  10023320  81157374

In [33]:
import random
from datetime import datetime, timedelta
import random

def gen_rating():
    # Generar un número aleatorio entre 0 y 5 con 1 solo decimal
    numero_aleatorio = round(random.uniform(0, 5), 1)
    # Mostrar el número aleatorio
    return numero_aleatorio

def gen_timestamp():
    # Generar un timestamp aleatorio dentro de un rango específico
    start_date = datetime(2024, 1, 15)
    end_date = datetime(2024, 4, 6)

    # Calcular un valor aleatorio entre start_date y end_date
    random_date = start_date + timedelta(seconds=random.randint(0, int((end_date - start_date).total_seconds())))

    # Mostrar el timestamp aleatorio
    return random_date

In [35]:
# Crea una nueva columna 'rating' y la llena con valores generados por la función 'gen_rating()' para cada 'movieID'.
watchs_data["rating"]=watchs_data["movieID"].apply(lambda x: gen_rating())
# Crea una nueva columna 'timestamp' y la llena con valores generados por la función 'gen_timestamp()' para cada 'userID'.
watchs_data["timestamp"]=watchs_data["userID"].apply(lambda x: gen_timestamp())

In [36]:
watchs_data.head()

    userID   movieID  rating           timestamp
0  1002331  80192187     1.1 2024-03-27 03:31:25
1  1002331  80210920     1.7 2024-01-28 03:27:00
2  1002331  81157374     2.7 2024-02-12 02:40:51
3  1002332  80192187     4.7 2024-03-30 02:32:10
4  1002332  80210920     4.7 2024-03-29 06:17:10

In [37]:
# Carga los datos del DataFrame 'watchs_data' en la tabla 'FactWatchs' de la base de datos.
# La conexión se establece a través de la variable 'conn'.
# 'if_exists='append'' indica que si la tabla ya existe, se agregarán las nuevas filas al final.
# 'index=False' evita que el índice del DataFrame sea escrito como una columna en la tabla.
watchs_data.to_sql("FactWatchs", conn, if_exists='append', index=False)

60

In [38]:
### SET FOREIGN_KEY_CHECKS = 0;
### SET FOREIGN_KEY_CHECKS = 1;